function makePosterSize(ax,w,h)
set(get(ax,"Parent"),"units","centimeters",...
    "Position",[1 1 w+10 h+10])

set(ax,"units","centimeters",...
    "position",[5 5 w h],...
    "fontsize",14,...
    "titlefontsizemultiplier",1,...
    "titlefontweight","normal",...
    "labelfontsizemultiplier",1,...
    "Linewidth",1);
end

