fP(1)=getFilePathsFromId("W6933c",...
        "XRD_2ThetaOmega",".xy");
fP(2)=getFilePathsFromId("W6957c",...
        "XRD_2ThetaOmega",".xy");
fP(3)=getFilePathsFromId("W6959c",...
        "XRD_2ThetaOmega",".xy");

for i = 1:3
    data{i} = getDiffraction(fP{i});
    x{i} = data{i}(:,1);
    y{i} = data{i}(:,2);
end

cs = [[0 0 0; 0 0 1; 1 0 0] [1;1;1]*.8];
name = ["pure Cr_2O_3";...
    "ex-situ Ga_2O_3";...
    "in-situ Ga_2O_3"];

%% Figure

f = figure("Units","centimeters","Position",[4 4 20 15]);
N = 3;
t = tiledlayout(f,2,N,"Units","centimeters",...
    "TileSpacing","compact",...
    "Padding","tight",...
    "OuterPosition",[2 2 14.64 10]);
xlabel(t,"2\theta (°)")
ylabel(t,"intensity (a.u.)")
ax0 = nexttile(t,1,[1 N]);
for i = 1:3
    p(i) = plot(x{i},y{i},...
        "LineWidth",1, ...
        "Color",cs(i,:), ...
        "DisplayName",name(i));
    hold on;
end
le = legend;
set(gca,...
        "YScale","log",...
        "YTick",[],...
        "LineWidth",1,...
        "FontSize",12);
axis tight
grid on
sgtitle("c-plane "+char(945)+"-Ga_2O_3 on buffer layer Cr_2O_3","Fontweight","bold")
lims0 = axis(ax0);

%% smaller plots

lims = {[18,22],[38,42],[83,92]};
cs2 = jet(N);
for l = 1:N
    pa(l) = patch([lims{l} flip(lims{l})],[lims0(3) lims0(3) lims0(4) lims0(4)],"k");
        pa(l).FaceAlpha = .1;
        pa(l).FaceColor = cs2(l,:);
        pa(l).HandleVisibility = "off";
end

for j = 1:N
    ax(j) = nexttile(t);
    for i = 1:3
        plot(x{i},y{i},...
            "LineWidth",1, ...
            "Color",cs(i,:), ...
            "HandleVisibility","off")
        hold on;
    end
    % legend
    set(gca,...
        "YScale","log",...
        "YTick",[],...
        "LineWidth",1,...
        "Color",[cs2(j,:) .1],...
        "FontSize",10,...
        "MinorGridLineWidth",.75,...
        "XColor",cs2(j,:)*.5);
    grid minor
    grid on
    xlim(lims{j})
    ylim([0 15e3])
end

le.FontSize = 10;

% 1st
xline(ax(1),18.89,":","LineWidth",1.5,...
    "DisplayName","(20.-1)_{"+char(946)+"-Ga2O3}",...
    "Alpha",1, ...
    "Color",[.5 .2 .6]);
le1 = legend(ax(1));
le1.FontSize = 10;
le1.Color = "w";
le1.Position = [0.17 0.42 0.26 0.07];

% 2nd
xline(ax(2),get2Theta([0 0 6],"Ga2O3"),":","LineWidth",2,...
    "DisplayName","(00.6)_{"+char(945)+"-Ga2O3}",...
    "Alpha",1,...
    "Color",[.8 .2 .2]);
xline(ax(2),38.32,":","LineWidth",1.5,...
    "DisplayName","(40.-2)_{"+char(946)+"-Ga2O3}",...
    "Alpha",1,...
    "Color",[.5 .2 .6]);
le2 = legend(ax(2));
le2.FontSize = 10;
le2.Color = "w";
le2.Position = [0.66 0.35 0.26 0.13];


exportgraphics(f,"_temp/c-plane_Ga2O3.png","Resolution",400)
