fP(1)=getFilePathsFromId("W6933c",...
        "XRD_2ThetaOmega",".xy");
% fP(1)=getFilePathsFromId("W6930c",...
%         "XRD_2ThetaOmega",".xy");
fP(2)=getFilePathsFromId("W6957c",...
        "XRD_2ThetaOmega",".xy");
fP(3)=getFilePathsFromId("W6959c",...
        "XRD_2ThetaOmega",".xy");

% offset
O = [0.06,0.06,0.03];
for i = 1:3
    data{i} = getDiffraction(fP{i});
    x{i} = data{i}(:,1)+O(i);
    y{i} = data{i}(:,2);
end

cs = [[0 0 0; 0 0 1; 1 0 0] [1;1;1]*.8];
name = ["pure Cr_2O_3";...
    "ex-situ Ga_2O_3";...
    "in-situ Ga_2O_3"];

%% Figure

f = figure("Units","centimeters","Position",[4 4 20 15]);
N = 3;
t = tiledlayout(f,2,N,"Units","centimeters",...
    "TileSpacing","compact",...
    "Padding","tight");
makeLatexSize(1,.6,t);
xlabel(t,"2\theta (°)")
ylabel(t,"counts (a.u.)")
ax0 = nexttile(t,1,[1 N]);
    formatAxes(ax0);
for i = 1:3
    p(i) = plot(x{i},y{i},...
        "LineWidth",1, ...
        "Color",cs(i,:), ...
        "DisplayName",name(i));
    hold on;
end
le = legend;
set(gca,...
        "YScale","log",...
        "YTickLabel",{},...
        "LineWidth",1,...
        "FontSize",12);
axis tight
grid on
sgtitle("{\itc}-plane \alpha-Ga_2O_3 on buffer layer Cr_2O_3","Fontweight","bold")
lims0 = axis(ax0);

%% smaller plots

lims = {[18,22],[38,42],[83,92]};
cs2 = jet(N);
for l = 1:N
    pa(l) = patch([lims{l} flip(lims{l})],[lims0(3) lims0(3) lims0(4) lims0(4)],"k");
        pa(l).FaceAlpha = .1;
        pa(l).FaceColor = cs2(l,:);
        pa(l).HandleVisibility = "off";
end

for j = 1:N
    ax(j) = nexttile(t);
    for i = 1:3
        plot(x{i},y{i},...
            "LineWidth",1, ...
            "Color",cs(i,:), ...
            "HandleVisibility","off")
        formatAxes(ax(j))
        hold on;
    end
    % legend
    set(gca,...
        "YScale","log",...
        "YTickLabel",{},...
        "LineWidth",1,...
        "Color",[cs2(j,:) .1],...
        "FontSize",10,...
        "MinorGridLineWidth",.75,...
        "XColor",cs2(j,:)*.5);
    grid minor
    grid on
    xlim(lims{j})
    ylim([0 15e3])
end

le.FontSize = 10;

% 1st chart
xline(ax(1),18.89,":","LineWidth",1.5,...
    "DisplayName","(20-1) {\beta-Ga_2O_3}",...
    "Alpha",1, ...
    "Color",[.5 .2 .6]);

xline(ax(1),19.11,"--","LineWidth",1.5,...
    "DisplayName","(002) {\kappa-Ga_2O_3}",...
    "Alpha",1,...
    "Color",[.2 .6 .5])
% le1 = legend(ax(1));
% le1.FontSize = 10;
% le1.Color = "w";
% le1.Position = [0.1114    0.32    0.2671    0.1170];

% 2nd chart
xline(ax(2),get2Theta([0 0 6],"Ga2O3"),":","LineWidth",2,...
    "DisplayName","(00.6)_{\alpha-Ga2O3}",...
    "Alpha",1,...
    "Color",[.8 .2 .2]);
xline(ax(2),38.32,":","LineWidth",1.5,...
    "DisplayName","(40.-2)_{\beta-Ga2O3}",...
    "Alpha",1,...
    "Color",[.5 .2 .6]);
xline(ax(2),38.77,"--","LineWidth",1.5,...
    "DisplayName","(004) {\kappa-Ga_2O_3}",...
    "Alpha",1,...
    "Color",[.2 .6 .5])
% le2 = legend(ax(2));
% le2.FontSize = 10;
% le2.Color = "w";
% le2.Position = [0.56 0.25 0.26 0.2];


% exportgraphics(f,"_temp/c-plane_Ga2O3.png","Resolution",400)
set(f,"renderer","painters")
% exportgraphics(f,"../Plots/Thesis/4/4_thetaomega_c.pdf")
% exportgraphics(f,"../Plots/Thesis/4/4_thetaomega_c.eps")

