function formatAxes(ax)

set(ax,...
    "Box","on",...
    "Fontsize",12,...
    "Titlefontsizemultiplier",1,...
    "titlefontweight","bold",...
    "labelfontsizemultiplier",1)

x = get(ax,"XAxis");
set(x,...
    "Fontsize",10)
set(get(x,"Label"),...
    "Fontsize",12)

y = get(ax,"YAxis");
set(y,...
    "Fontsize",10 ...
    )
set(get(y,"Label"),...
    "Fontsize",12)

end

