function output = getChromiumVector(hkl_in,hkl_out)
q_fh = ...
    @(hkl,a,c) ...
    sqrt(...
    4/3*(hkl(1)^2+hkl(2)^2+hkl(1)*hkl(2))/a^2 + ...
    hkl(3)^2/c^2);
    % calculates reciprocal lattice vector

a_Cr2O3 = 4.958; % angstrom
c_Cr2O3 = 13.593; % angstrom

q_Cr2O3_lit_fh = ...    
    @(hkl_par,hkl_perp) ...
    [...
    q_fh(hkl_par,a_Cr2O3,c_Cr2O3);...
    q_fh(hkl_perp,a_Cr2O3,c_Cr2O3)...
    ] * 10; % nm^{-1}

output = q_Cr2O3_lit_fh(hkl_in,hkl_out);

end

