function output = getSapphireVector(hkl_in,hkl_out)
q_fh = ...
    @(hkl,a,c) ...
    sqrt(...
    4/3*(hkl(1)^2+hkl(2)^2+hkl(1)*hkl(2))/a^2 + ...
    hkl(3)^2/c^2);
    % calculates reciprocal lattice vector

a_Al2O3 = 4.755; % angstrom
c_Al2O3 = 12.99; % angstrom

q_Al2O3_lit_fh = ...
    @(hkl_par,hkl_perp) ...
    [...
    q_fh(hkl_par,a_Al2O3,c_Al2O3);...
    q_fh(hkl_perp,a_Al2O3,c_Al2O3)...
    ] * 10; % nm^{-1}

output = q_Al2O3_lit_fh(hkl_in,hkl_out);

end

