function formatAxes(ax)
LabelSize = 12;
TickSize = 10;

set(ax,...
    "Box","on",...
    "linewidth",1,...
    "gridlinewidth",.75,...
    "Fontsize",LabelSize,...
    "Titlefontsizemultiplier",1,...
    "titlefontweight","bold",...
    "labelfontsizemultiplier",LabelSize/TickSize)

x = get(ax,"XAxis");
    set(x,...
        "Fontsize",TickSize)
    % set(get(x,"Label"),...
    %     "Fontsize",LabelSize)

y = get(ax,"YAxis");
    set(y,...
        "Fontsize",TickSize ...
        )
    % set(get(y,"Label"),...
    %     "Fontsize",LabelSize)

if ~isempty(ax.Legend)
    ax.Legend.FontSize = TickSize;
    ax.Legend.Title.FontSize = TickSize;
    ax.Legend.Title.FontWeight = "normal";
end

end

